name: Clang Tidy
# Set the type of machine to run on
runs-on: ubuntu-latest

steps:
  # Checks out a copy of your repository on the ubuntu-latest machine
  - name: Checkout code
    uses: actions/checkout@v2

  - name: clang-tidy-action
    uses: asarium/clang-tidy-action@v1.0
