name: Clang Tidy - Android

on:
  pull_request_target: 
    types: [assigned, opened, edited, synchronize, reopened ,ready_for_review]

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  super-lint:
    # Name the Job
    name: Lint code base - Android
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get changed files
        uses: PatriceJiang/paths-filter@master
        id: listchanged
        with:
          list-files: shell
          filters: |
            source:
              - added|modified: '**/*.cpp'
              - added|modified: '**/*.h'
              - added|modified: '**/*.hpp'
              - added|modified: '**/*.m'
              - added|modified: '**/*.mm'
              - added|modified: '**/*.c'
              - exclude: 'cocos/editor-support/dragonbones/**'
              - exclude: 'cocos/base/etc1.*'
              - exclude: 'cocos/base/etc2.*'
            allChanges:
              - added|modified|deleted: '**'
            skipedDebug:
              - added|modified|deleted: '**'
              - exclude: 'cocos/editor-support/dragonbones/**'
      - name: Install CMake & Clang Tidy
        run: |
          sudo apt install -y cmake llvm clang-tidy-11
      - name: Install Android NDK 21
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e
          add-to-path: false
      - name: Generate Compile database
        shell: bash
        run: |
          EXT_VERSION=`grep version external/config.json  |awk -F'"' '{print $4}'`
          rm external/config.json
          git clone --branch $EXT_VERSION --depth 1 https://github.com/cocos-creator/engine-native-external external
          utils/generate_compile_commands_android.sh
      - name: Generate clang-fix.yaml
        shell: bash
        if: ${{ steps.listchanged.outputs.source == 'true' }}
        run: |
          CPP="${{ steps.listchanged.outputs.source_files }}"
          FILTERED=`node .github/workflows/filter_by_cdb.js $CPP`
          if [[ "$FILTERED-xxx" == "-xxx" ]]; then
            echo "no source files match"
          else
            $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/clang-tidy --format-style=file --export-fixes=clang-fixes.yaml $FILTERED
          fi
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - name: clang-tidy-action
        uses: PatriceJiang/clang-tidy-action@github-api
        if: hashFiles('clang-fixes.yaml') != ''
        with:
          fixesFile: clang-fixes.yaml
          noFailOnIssue: false
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          error-limit: 200
